/* Injects deployment config into config.js from environment variables.
   Run automatically by Vercel/Netlify/Cloudflare via the build command.
   Unset variables fall back to the defaults baked into index.html. */
import { writeFileSync } from "node:fs";

const KEYS = ["WARP_CA", "WARP_X", "WARP_GITHUB", "WARP_EXPLORER"];
const env = process.env;

const body = KEYS
  .map(k => `window.__${k}__ = ${JSON.stringify(env[k] ?? "")};`)
  .join("\n");

writeFileSync(
  "config.js",
  `/* generated by build.mjs — do not edit by hand */\n${body}\n`,
  "utf8"
);

const ca = env.WARP_CA;
console.log(
  ca
    ? `config.js written · contract ${ca.slice(0, 6)}…${ca.slice(-4)}`
    : "config.js written · WARP_CA unset, the CA slot stays empty"
);
